# Generated by Django 2.2.4 on 2019-08-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='netmask',
            field=models.GenericIPAddressField(protocol='ipv4'),
        ),
        migrations.AlterField(
            model_name='network',
            name='subnet',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True),
        ),
    ]
