# Generated by Django 2.2.4 on 2019-08-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20190820_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('SRV', 'Server'), ('HT', 'Host')], default='HT', max_length=3)),
            ],
            options={
                'db_table': 'node',
            },
        ),
    ]
