# Generated by Django 2.2.4 on 2019-08-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='network.Network'),
        ),
    ]
