# Generated by Django 2.2.4 on 2019-08-21 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20190821_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='netmask',
        ),
        migrations.AddField(
            model_name='network',
            name='cidr',
            field=models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(default='192.168.0.254', protocol='ipv4', unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='address',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True),
        ),
    ]
