# Generated by Django 2.2.4 on 2019-08-21 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20190821_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='vlan',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)]),
        ),
    ]
