# Generated by Django 2.2.4 on 2019-08-22 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20190821_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='cidr',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AlterField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(protocol='ipv4', unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='vlan',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)]),
        ),
    ]
